name: Build and Run Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies and build frontend
      run: |
        cd frontend-web
        npm install
        npm run build

  run_backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies and run backend
      run: |
        cd backend
        npm install
        npm run ci # run the ci-check.ts script